# Makefile generated by the project manager
#


# GENERATED: Thu Dec 18 15:26:02 China Standard Time 2008
# DO NOT EDIT - file is regenerated whenever the project changes


## core information

ifeq ($(wildcard Makefile.mk),)
PRJ_DIR        = ..
else
PRJ_DIR        = .
endif
PRJ_FILE       = 8548_bios.wpj
PRJ_FULL_PATH  = E:/cc/705_725/OnsPlatform/bsp_cmm/bsp_prj/PPC8458
PRJ_TYPE       = vxWorks
PRJ_OBJS       = sysALib.o sysLib.o usrAppInit.o usrRtpAppInit.o prjConfig.o linkSyms.o sysMotTsecEnd.o motTsecEnd.o bspDriver.o bspChassis.o BspSpi.o sysTffs.o usrTffs.o ftpd6Lib.o biosmain.o hardware.o ivm_core.o ispvm_ui.o biosmain.o excArchLib.o
PRJ_MAKEFILE   = $(PRJ_DIR)/Makefile.mk
BOOT_OBJS      = romInit.o romStart.o $(BOOT_EXTRA)
BUILD_SPEC     = default_romCompress
BSP_DIR        = $(TGT_DIR)/config/cds8548
TGT_DIR        = $(WIND_BASE)/target



## set searching directories for dependencies

vpath %.c $(BSP_DIR)
vpath %.cpp $(BSP_DIR)
vpath %.cxx $(BSP_DIR)
vpath %.s $(BSP_DIR)


## build-configuration info

ifeq ($(BUILD_SPEC),default)
CPU            = PPC85XX
TOOL           = gnu
TOOL_FAMILY    = gnu
DEFAULT_RULE   = vxWorks
OPT            = 
endif

ifeq ($(BUILD_SPEC),default_rom)
CPU            = PPC85XX
TOOL           = gnu
TOOL_FAMILY    = gnu
DEFAULT_RULE   = vxWorks_rom
OPT            = 
endif

ifeq ($(BUILD_SPEC),default_romCompress)
CPU            = PPC85XX
TOOL           = gnu
TOOL_FAMILY    = gnu
DEFAULT_RULE   = vxWorks_romCompress
OPT            = 
endif

ifeq ($(BUILD_SPEC),default_romResident)
CPU            = PPC85XX
TOOL           = gnu
TOOL_FAMILY    = gnu
DEFAULT_RULE   = vxWorks_romResident
OPT            = 
endif


## Memory adresses variables

RAM_LOW_ADRS = 03e00000
RAM_HIGH_ADRS = 04000000
LOCAL_MEM_LOCAL_ADRS = 00000000
DATA_SEG_ALIGN = 1

## component-configuration info

COMPONENTS = INCLUDE_AIM_CACHE \
	INCLUDE_ANSI_ABORT \
	INCLUDE_ANSI_ABS \
	INCLUDE_ANSI_ASSERT \
	INCLUDE_ANSI_ATOF \
	INCLUDE_ANSI_BSEARCH \
	INCLUDE_ANSI_CTYPE \
	INCLUDE_ANSI_LOCALE \
	INCLUDE_ANSI_LONGJMP \
	INCLUDE_ANSI_MATH \
	INCLUDE_ANSI_MEMCHR \
	INCLUDE_ANSI_MEMCMP \
	INCLUDE_ANSI_MEMCPY \
	INCLUDE_ANSI_MEMMOVE \
	INCLUDE_ANSI_MEMSET \
	INCLUDE_ANSI_STDIO \
	INCLUDE_ANSI_STDIO_EXTRA \
	INCLUDE_ANSI_STDLIB \
	INCLUDE_ANSI_STDLIB_NUMBERS \
	INCLUDE_ANSI_STRCASECMP \
	INCLUDE_ANSI_STRCAT \
	INCLUDE_ANSI_STRCMP \
	INCLUDE_ANSI_STRCPY \
	INCLUDE_ANSI_STRDUP \
	INCLUDE_ANSI_STRERROR \
	INCLUDE_ANSI_STRING \
	INCLUDE_ANSI_STRLCPY \
	INCLUDE_ANSI_STRLEN \
	INCLUDE_ANSI_STRNCASECMP \
	INCLUDE_ANSI_STRNCAT \
	INCLUDE_ANSI_STRNCMP \
	INCLUDE_ANSI_STRNCPY \
	INCLUDE_ANSI_STRTOD \
	INCLUDE_ANSI_TIME \
	INCLUDE_APPL_LOG_UTIL \
	INCLUDE_ARP_API \
	INCLUDE_AUX_CLK \
	INCLUDE_AVL_UINT_TREES \
	INCLUDE_BASE_KERNEL \
	INCLUDE_BLIB \
	INCLUDE_BLIB_ARCH \
	INCLUDE_BOOT_LINE_INIT \
	INCLUDE_BSD_SOCKET \
	INCLUDE_BSP_MACROS \
	INCLUDE_BUF_MGR \
	INCLUDE_CACHE_ENABLE \
	INCLUDE_CACHE_L2 \
	INCLUDE_CACHE_L2_ENABLE \
	INCLUDE_CACHE_SUPPORT \
	INCLUDE_CHECKSUM \
	INCLUDE_CLASS_LIB \
	INCLUDE_COPROCESSOR \
	INCLUDE_COPROCESSOR_SHOW \
	INCLUDE_CTORS_DTORS \
	INCLUDE_DEBUG \
	INCLUDE_DEFERRED_INTERRUPT_ENABLE \
	INCLUDE_DEVICE_MANAGER \
	INCLUDE_DHCPC_LEASE_CLEAN \
	INCLUDE_DLL \
	INCLUDE_DOMAIN_INIT \
	INCLUDE_DOSFS \
	INCLUDE_DOSFS_CHKDSK \
	INCLUDE_DOSFS_DIR_FIXED \
	INCLUDE_DOSFS_DIR_VFAT \
	INCLUDE_DOSFS_FAT \
	INCLUDE_DOSFS_FMT \
	INCLUDE_DOSFS_MAIN \
	INCLUDE_EDR_PM \
	INCLUDE_EDR_STUB \
	INCLUDE_EDR_SYSDBG_FLAG \
	INCLUDE_END \
	INCLUDE_END_POLLED_STATS \
	INCLUDE_ENV_VARS \
	INCLUDE_ERF \
	INCLUDE_ETHERNET \
	INCLUDE_EXC_HANDLING \
	INCLUDE_EXC_TASK \
	INCLUDE_FLOATING_POINT \
	INCLUDE_FORMATTED_IO \
	INCLUDE_FORMATTED_OUT_BASIC \
	INCLUDE_FP_TYPE \
	INCLUDE_FS_EVENT_UTIL \
	INCLUDE_FS_MONITOR \
	INCLUDE_GETADDRINFO \
	INCLUDE_GETIFADDRS \
	INCLUDE_GETSERVBYNAME \
	INCLUDE_GNU_INTRINSICS \
	INCLUDE_GTF \
	INCLUDE_GTF_TIMER_START \
	INCLUDE_HANDLE_SHOW \
	INCLUDE_HASH \
	INCLUDE_HOOKS \
	INCLUDE_HOST_TBL \
	INCLUDE_HWMEM_ALLOC \
	INCLUDE_HW_FP \
	INCLUDE_ICMPV4 \
	INCLUDE_ICMP_SHOW \
	INCLUDE_IF \
	INCLUDE_IFINDEX \
	INCLUDE_IFLIB \
	INCLUDE_IGMP \
	INCLUDE_IGMP_SHOW \
	INCLUDE_INETLIB \
	INCLUDE_IO_SYSTEM \
	INCLUDE_IPATTACH \
	INCLUDE_IPV4 \
	INCLUDE_JOB_QUEUE \
	INCLUDE_JOB_TASK \
	INCLUDE_KERNEL \
	INCLUDE_KERNEL_ARCH \
	INCLUDE_KERN_RANDOM \
	INCLUDE_LINKBUFPOOL \
	INCLUDE_LOADER \
	INCLUDE_LOADER_CODE \
	INCLUDE_LOGGING \
	INCLUDE_LOOPBACK \
	INCLUDE_LSTLIB \
	INCLUDE_MEMORY_CONFIG \
	INCLUDE_MEM_MGR_BASIC \
	INCLUDE_MEM_MGR_FULL \
	INCLUDE_MIB2_IF \
	INCLUDE_MMU_BASIC \
	INCLUDE_MMU_GLOBAL_MAP \
	INCLUDE_MODULE_MANAGER \
	INCLUDE_MSG_Q \
	INCLUDE_MSG_Q_CREATE_DELETE \
	INCLUDE_MSG_Q_EVENTS \
	INCLUDE_MSG_Q_INFO \
	INCLUDE_MUX \
	INCLUDE_NBIO_LOG \
	INCLUDE_NETBUFLIB \
	INCLUDE_NETBUFPOOL \
	INCLUDE_NETMASK_GET \
	INCLUDE_NETPOOLSHOW \
	INCLUDE_NETWORK \
	INCLUDE_NET_BOOT \
	INCLUDE_NET_BOOT_CONFIG \
	INCLUDE_NET_DAEMON \
	INCLUDE_NET_FUNCBIND \
	INCLUDE_NET_HOST_SETUP \
	INCLUDE_NET_HOST_SHOW \
	INCLUDE_NET_IF_SHOW \
	INCLUDE_NET_INIT \
	INCLUDE_NET_MD5 \
	INCLUDE_NET_POOL \
	INCLUDE_NET_ROUTE_SHOW \
	INCLUDE_NET_ROUTE_SHOW_SNPRINTF \
	INCLUDE_NET_SHOW \
	INCLUDE_NET_SYSCTL \
	INCLUDE_OBJ_LIB \
	INCLUDE_OBJ_LIB_ARCH \
	INCLUDE_OFFSET_SYMBOLS \
	INCLUDE_OLDROUTE \
	INCLUDE_PING \
	INCLUDE_PIPES \
	INCLUDE_PLB_BUS \
	INCLUDE_POOL \
	INCLUDE_POSIX_CLOCKS \
	INCLUDE_POSIX_DIRLIB \
	INCLUDE_POSIX_FS \
	INCLUDE_PTYDRV \
	INCLUDE_Q_FIFO \
	INCLUDE_Q_LIB \
	INCLUDE_Q_PRI_BMAP \
	INCLUDE_Q_PRI_DELTA \
	INCLUDE_Q_PRI_LIST \
	INCLUDE_RAWFS \
	INCLUDE_RAWV4 \
	INCLUDE_REBOOT_HOOKS \
	INCLUDE_RNG_BUF \
	INCLUDE_ROUTE \
	INCLUDE_ROUTE_STORAGE \
	INCLUDE_ROUTING_SOCKET \
	INCLUDE_SELECT \
	INCLUDE_SELECT_SUPPORT \
	INCLUDE_SEM_BINARY \
	INCLUDE_SEM_BINARY_CREATE \
	INCLUDE_SEM_COUNTING \
	INCLUDE_SEM_COUNTING_CREATE \
	INCLUDE_SEM_DELETE \
	INCLUDE_SEM_EVENTS \
	INCLUDE_SEM_INFO \
	INCLUDE_SEM_LIB \
	INCLUDE_SEM_MUTEX \
	INCLUDE_SEM_MUTEX_CREATE \
	INCLUDE_SET \
	INCLUDE_SHELL \
	INCLUDE_SHELL_INTERP_C \
	INCLUDE_SHELL_VI_MODE \
	INCLUDE_SIGNALS \
	INCLUDE_SIGNAL_ARCH \
	INCLUDE_SIO \
	INCLUDE_SLL \
	INCLUDE_SOCKLIB \
	INCLUDE_SPE \
	INCLUDE_SPY \
	INCLUDE_STANDALONE_SYM_TBL \
	INCLUDE_STDIO \
	INCLUDE_STRICMP \
	INCLUDE_SW_FP \
	INCLUDE_SYM_TBL \
	INCLUDE_SYM_TBL_INIT \
	INCLUDE_SYM_TBL_SHOW \
	INCLUDE_SYSCLK_INIT \
	INCLUDE_SYSCTL \
	INCLUDE_SYSHW_INIT \
	INCLUDE_SYS_START \
	INCLUDE_TASK_CREATE_DELETE \
	INCLUDE_TASK_HOOKS \
	INCLUDE_TASK_INFO \
	INCLUDE_TASK_RESTART \
	INCLUDE_TASK_SHOW \
	INCLUDE_TASK_VARS \
	INCLUDE_TCPV4 \
	INCLUDE_TCP_SHOW \
	INCLUDE_TELNET \
	INCLUDE_TIMEX \
	INCLUDE_TTY_DEV \
	INCLUDE_TYLIB \
	INCLUDE_UDPV4 \
	INCLUDE_UDP_SHOW \
	INCLUDE_UNLOADER \
	INCLUDE_USER_APPL \
	INCLUDE_VXBUS \
	INCLUDE_VXBUS_ACTIVATE \
	INCLUDE_VXBUS_INIT \
	INCLUDE_VXEVENTS \
	INCLUDE_VX_TRADITIONAL_SCHEDULER \
	INCLUDE_WATCHDOGS \
	INCLUDE_WATCHDOGS_CREATE_DELETE \
	INCLUDE_WDB \
	INCLUDE_WDB_BANNER \
	INCLUDE_WDB_BP \
	INCLUDE_WDB_BP_SYNC \
	INCLUDE_WDB_COMM_NETWORK \
	INCLUDE_WDB_CTXT \
	INCLUDE_WDB_DIRECT_CALL \
	INCLUDE_WDB_EVENTPOINTS \
	INCLUDE_WDB_EVENTS \
	INCLUDE_WDB_EXC_NOTIFY \
	INCLUDE_WDB_EXIT_NOTIFY \
	INCLUDE_WDB_FUNC_CALL \
	INCLUDE_WDB_GOPHER \
	INCLUDE_WDB_MDL_SYM_SYNC \
	INCLUDE_WDB_MEM \
	INCLUDE_WDB_POST_KERNEL_INIT \
	INCLUDE_WDB_REG \
	INCLUDE_WDB_START_NOTIFY \
	INCLUDE_WDB_TASK \
	INCLUDE_WDB_TASK_BP \
	INCLUDE_WDB_TASK_HOOKS \
	INCLUDE_WDB_TASK_REG \
	INCLUDE_WDB_USER_EVENT \
	INCLUDE_WDB_VIO \
	INCLUDE_WDB_VIO_LIB \
	INCLUDE_XBD

MANAGED_LIBS = 
COMPONENT_LIBS = 

PROJECT_LINK_SYMDEFS = 


include $(TGT_DIR)/h/make/defs.project


## build-configuration info

ifeq ($(BUILD_SPEC),default)
AR               = arppc
AS               = ccppc
BOOT_EXTRA       = 
CC               = ccppc
CC_ARCH_SPEC     = -mcpu=8540 -mstrict-align -msoft-float -mabi=no-spe
CFLAGS           = -g -mcpu=8540 -mstrict-align -msoft-float -mabi=no-spe -fno-builtin -Wall -DCPU=PPC85XX -DTOOL_FAMILY=gnu -DTOOL=gnu -DPRJ_BUILD -D_WRS_KERNEL -I $(PRJ_DIR) -I $(PRJ_DIR)/../cds8548 -I $(TGT_DIR)/h -I $(TGT_DIR)/config/comps/src -I $(TGT_DIR)/h/wrn/coreip -I $(TGT_DIR)/src/drv -I $(WIND_HOME)/components/windml-4.2/h -I $(WIND_HOME)/components/dcom-2.3/h -I $(WIND_HOME)/components/opc-3.1/h -I $(WIND_HOME)/components/webcli-4.5/target/h -I $(WIND_HOME)/components/webservices-1.4/h -I $(WIND_HOME)/components/windml-4.2/osconfig/vxworks/src -I $(WIND_HOME)/components/windml-4.2/osconfig/vxworks/h
CFLAGS_AS        = -g -mcpu=8540 -mstrict-align -msoft-float -mabi=no-spe -fno-builtin -xassembler-with-cpp -DCPU=PPC85XX -DTOOL_FAMILY=gnu -DTOOL=gnu -DPRJ_BUILD -D_WRS_KERNEL -I $(PRJ_DIR) -I $(PRJ_DIR)/../cds8548 -I $(TGT_DIR)/h -I $(TGT_DIR)/config/comps/src -I $(TGT_DIR)/h/wrn/coreip -I $(TGT_DIR)/src/drv -I $(WIND_HOME)/components/windml-4.2/h -I $(WIND_HOME)/components/dcom-2.3/h -I $(WIND_HOME)/components/opc-3.1/h -I $(WIND_HOME)/components/webcli-4.5/target/h -I $(WIND_HOME)/components/webservices-1.4/h -I $(WIND_HOME)/components/windml-4.2/osconfig/vxworks/src -I $(WIND_HOME)/components/windml-4.2/osconfig/vxworks/h
CFLAGS_AS_PROJECT = -g -mcpu=8540 -mstrict-align -msoft-float -mabi=no-spe -ansi -fno-builtin -I$(WIND_HOME)/components/windml-4.2/h -I$(WIND_HOME)/components/dcom-2.3/h -I$(WIND_HOME)/components/opc-3.1/h -I$(WIND_HOME)/components/webcli-4.5/target/h -I$(WIND_HOME)/components/webservices-1.4/h -I$(WIND_HOME)/components/windml-4.2/osconfig/vxworks/src -I$(WIND_HOME)/components/windml-4.2/osconfig/vxworks/h -I. -I$(TGT_DIR)/config/all -I$(TGT_DIR)/h -I$(TGT_DIR)/h/wrn/coreip -I$(TGT_DIR)/src/config -I$(TGT_DIR)/config/comps/src -I$(TGT_DIR)/config/comps/src/dosfs2 -I$(TGT_DIR)/src/drv -DCPU=PPC85XX -DTOOL_FAMILY=gnu -DTOOL=gnu -D_WRS_KERNEL -xassembler-with-cpp
CFLAGS_PROJECT   = -g -mcpu=8540 -mstrict-align -msoft-float -mabi=no-spe -ansi -fno-builtin -Wall -I$(WIND_HOME)/components/windml-4.2/h -I$(WIND_HOME)/components/dcom-2.3/h -I$(WIND_HOME)/components/opc-3.1/h -I$(WIND_HOME)/components/webcli-4.5/target/h -I$(WIND_HOME)/components/webservices-1.4/h -I$(WIND_HOME)/components/windml-4.2/osconfig/vxworks/src -I$(WIND_HOME)/components/windml-4.2/osconfig/vxworks/h -I. -I$(TGT_DIR)/config/all -I$(TGT_DIR)/h -I$(TGT_DIR)/h/wrn/coreip -I$(TGT_DIR)/src/config -I$(TGT_DIR)/config/comps/src -I$(TGT_DIR)/config/comps/src/dosfs2 -I$(TGT_DIR)/src/drv -DCPU=PPC85XX -DTOOL_FAMILY=gnu -DTOOL=gnu -D_WRS_KERNEL
CPP              = ccppc -E -P
EXTRA_MODULES    = $(SUB_TARGETS)
LD               = ldppc
LDFLAGS          = -X -N
LD_LINK_PATH     = -L$(TGT_DIR)/lib/ppc/PPC85XX/gnu -L$(TGT_DIR)/lib/ppc/PPC85XX/common -L$(TGT_DIR)/lib/ppc/PPC32/sfgnu_ppc85XX -L$(TGT_DIR)/lib/ppc/PPC32/sfcommon_ppc85XX -L$(TGT_DIR)/lib/ppc/PPC32/sfgnu -L$(TGT_DIR)/lib/ppc/PPC32/sfcommon -L$(WS_ROOT_DIR)/obj/vxworks-6.3/krnl/lib/ppc/PPC32/gnu -L$(WS_ROOT_DIR)/obj/vxworks-6.3/krnl/lib/ppc/PPC32/common -L$(WIND_HOME)/components/obj/vxworks-6.3/krnl/lib/ppc/PPC32/gnu -L$(WIND_HOME)/components/obj/vxworks-6.3/krnl/lib/ppc/PPC32/common
LD_PARTIAL       = ccppc -r -nostdlib -Wl,-X
LD_PARTIAL_FLAGS = -X -r
LIBS             = $(VX_OS_LIBS)
NM               = nmppc
OPTION_DEFINE_MACRO = -D
OPTION_DEPEND    = -M -w
OPTION_GENERATE_DEPENDENCY_FILE = -MD
OPTION_INCLUDE_DIR = -I
OPTION_LANG_C    = -xc
OPTION_UNDEFINE_MACRO = -U
ROM_LINK_ADRS    = fff00000
ROM_WARM_ADRS    = fff00108 # ROM warm entry address
SIZE             = sizeppc
TOOL_FAMILY      = gnu
USR_ENTRY        = usrInit
VMA_START        = 0x0
POST_BUILD_RULE  = 
POST_HEX_BUILD_RULE = 
endif

ifeq ($(BUILD_SPEC),default_rom)
AR               = arppc
AS               = ccppc
BOOT_EXTRA       = 
CC               = ccppc
CC_ARCH_SPEC     = -mcpu=8540 -mstrict-align -msoft-float -mabi=no-spe
CFLAGS           = -g -mcpu=8540 -mstrict-align -msoft-float -mabi=no-spe -ansi -fno-builtin -Wall -I$(PRJ_DIR) -I$(PRJ_DIR)/../cds8548 -I$(TGT_DIR)/h -I$(TGT_DIR)/config/comps/src -I$(TGT_DIR)/h/wrn/coreip -I$(TGT_DIR)/src/drv -DCPU=PPC85XX -DTOOL_FAMILY=gnu -DTOOL=gnu -DPRJ_BUILD -D_WRS_KERNEL -I$(WIND_HOME)/components/windml-4.2/h -I$(WIND_HOME)/components/dcom-2.3/h -I$(WIND_HOME)/components/opc-3.1/h -I$(WIND_HOME)/components/webcli-4.5/target/h -I$(WIND_HOME)/components/webservices-1.4/h -I$(WIND_HOME)/components/windml-4.2/osconfig/vxworks/src -I$(WIND_HOME)/components/windml-4.2/osconfig/vxworks/h
CFLAGS_AS        = -g -mcpu=8540 -mstrict-align -msoft-float -mabi=no-spe -ansi -fno-builtin -xassembler-with-cpp -I$(PRJ_DIR) -I$(PRJ_DIR)/../cds8548 -I$(TGT_DIR)/h -I$(TGT_DIR)/config/comps/src -I$(TGT_DIR)/h/wrn/coreip -I$(TGT_DIR)/src/drv -DCPU=PPC85XX -DTOOL_FAMILY=gnu -DTOOL=gnu -DPRJ_BUILD -D_WRS_KERNEL -I$(WIND_HOME)/components/windml-4.2/h -I$(WIND_HOME)/components/dcom-2.3/h -I$(WIND_HOME)/components/opc-3.1/h -I$(WIND_HOME)/components/webcli-4.5/target/h -I$(WIND_HOME)/components/webservices-1.4/h -I$(WIND_HOME)/components/windml-4.2/osconfig/vxworks/src -I$(WIND_HOME)/components/windml-4.2/osconfig/vxworks/h
CFLAGS_AS_PROJECT = -g -mcpu=8540 -mstrict-align -msoft-float -mabi=no-spe -ansi -fno-builtin -I$(WIND_HOME)/components/windml-4.2/h -I$(WIND_HOME)/components/dcom-2.3/h -I$(WIND_HOME)/components/opc-3.1/h -I$(WIND_HOME)/components/webcli-4.5/target/h -I$(WIND_HOME)/components/webservices-1.4/h -I$(WIND_HOME)/components/windml-4.2/osconfig/vxworks/src -I$(WIND_HOME)/components/windml-4.2/osconfig/vxworks/h -I. -I$(TGT_DIR)/config/all -I$(TGT_DIR)/h -I$(TGT_DIR)/h/wrn/coreip -I$(TGT_DIR)/src/config -I$(TGT_DIR)/config/comps/src -I$(TGT_DIR)/config/comps/src/dosfs2 -I$(TGT_DIR)/src/drv -DCPU=PPC85XX -DTOOL_FAMILY=gnu -DTOOL=gnu -D_WRS_KERNEL -xassembler-with-cpp
CFLAGS_PROJECT   = -g -mcpu=8540 -mstrict-align -msoft-float -mabi=no-spe -ansi -fno-builtin -Wall -I$(WIND_HOME)/components/windml-4.2/h -I$(WIND_HOME)/components/dcom-2.3/h -I$(WIND_HOME)/components/opc-3.1/h -I$(WIND_HOME)/components/webcli-4.5/target/h -I$(WIND_HOME)/components/webservices-1.4/h -I$(WIND_HOME)/components/windml-4.2/osconfig/vxworks/src -I$(WIND_HOME)/components/windml-4.2/osconfig/vxworks/h -I. -I$(TGT_DIR)/config/all -I$(TGT_DIR)/h -I$(TGT_DIR)/h/wrn/coreip -I$(TGT_DIR)/src/config -I$(TGT_DIR)/config/comps/src -I$(TGT_DIR)/config/comps/src/dosfs2 -I$(TGT_DIR)/src/drv -DCPU=PPC85XX -DTOOL_FAMILY=gnu -DTOOL=gnu -D_WRS_KERNEL
CPP              = ccppc -E -P
EXTRA_MODULES    = $(SUB_TARGETS)
HEX_FLAGS        = 
LD               = ldppc
LDFLAGS          = -X -N
LD_LINK_PATH     = -L$(TGT_DIR)/lib/ppc/PPC85XX/gnu -L$(TGT_DIR)/lib/ppc/PPC85XX/common -L$(TGT_DIR)/lib/ppc/PPC32/sfgnu_ppc85XX -L$(TGT_DIR)/lib/ppc/PPC32/sfcommon_ppc85XX -L$(TGT_DIR)/lib/ppc/PPC32/sfgnu -L$(TGT_DIR)/lib/ppc/PPC32/sfcommon -L$(WS_ROOT_DIR)/obj/vxworks-6.3/krnl/lib/ppc/PPC32/gnu -L$(WS_ROOT_DIR)/obj/vxworks-6.3/krnl/lib/ppc/PPC32/common -L$(WIND_HOME)/components/obj/vxworks-6.3/krnl/lib/ppc/PPC32/gnu -L$(WIND_HOME)/components/obj/vxworks-6.3/krnl/lib/ppc/PPC32/common
LD_PARTIAL       = ccppc -r -nostdlib -Wl,-X
LD_PARTIAL_FLAGS = -X -r
LIBS             = $(VX_OS_LIBS)
NM               = nmppc
OPTION_DEFINE_MACRO = -D
OPTION_DEPEND    = -M -w
OPTION_GENERATE_DEPENDENCY_FILE = -MD
OPTION_INCLUDE_DIR = -I
OPTION_LANG_C    = -xc
OPTION_UNDEFINE_MACRO = -U
ROM_LINK_ADRS    = fff00000
ROM_SIZE         = 00100000 # number of bytes of ROM space
ROM_TEXT_ADRS    = fff00100 # ROM entry address
ROM_WARM_ADRS    = fff00108 # ROM warm entry address
SIZE             = sizeppc
TOOL_FAMILY      = gnu
USR_ENTRY        = usrInit
VMA_START        = 0x0
POST_BUILD_RULE  = 
POST_HEX_BUILD_RULE = 
endif

ifeq ($(BUILD_SPEC),default_romCompress)
AR               = arppc
AS               = ccppc
BOOT_EXTRA       = 
CC               = ccppc
CC_ARCH_SPEC     = -mcpu=8540 -mstrict-align -msoft-float -mabi=no-spe
CFLAGS           = -g -mcpu=8540 -mstrict-align -msoft-float -mabi=no-spe -fno-builtin -Wall -DCPU=PPC85XX -DTOOL_FAMILY=gnu -DTOOL=gnu -DPRJ_BUILD -D_WRS_KERNEL -DBIOS_APP -I $(PRJ_DIR) -I $(PRJ_DIR)/../../bsp_files/PPC8548 -I $(TGT_DIR)/h -I $(TGT_DIR)/config/comps/src -I $(TGT_DIR)/h/wrn/coreip -I $(TGT_DIR)/src/drv
CFLAGS_AS        = -g -mcpu=8540 -mstrict-align -msoft-float -mabi=no-spe -fno-builtin -xassembler-with-cpp -DCPU=PPC85XX -DTOOL_FAMILY=gnu -DTOOL=gnu -DPRJ_BUILD -D_WRS_KERNEL -I $(PRJ_DIR) -I $(PRJ_DIR)/../../bsp_files/PPC8548 -I $(TGT_DIR)/h -I $(TGT_DIR)/config/comps/src -I $(TGT_DIR)/h/wrn/coreip -I $(TGT_DIR)/src/drv
CFLAGS_AS_PROJECT = -g -mcpu=8540 -mstrict-align -msoft-float -mabi=no-spe -ansi -fno-builtin -I$(WIND_HOME)/components/windml-4.2/h -I$(WIND_HOME)/components/dcom-2.3/h -I$(WIND_HOME)/components/opc-3.1/h -I$(WIND_HOME)/components/webcli-4.5/target/h -I$(WIND_HOME)/components/webservices-1.4/h -I$(WIND_HOME)/components/windml-4.2/osconfig/vxworks/src -I$(WIND_HOME)/components/windml-4.2/osconfig/vxworks/h -I. -I$(TGT_DIR)/config/all -I$(TGT_DIR)/h -I$(TGT_DIR)/h/wrn/coreip -I$(TGT_DIR)/src/config -I$(TGT_DIR)/config/comps/src -I$(TGT_DIR)/config/comps/src/dosfs2 -I$(TGT_DIR)/src/drv -DCPU=PPC85XX -DTOOL_FAMILY=gnu -DTOOL=gnu -D_WRS_KERNEL -xassembler-with-cpp
CFLAGS_PROJECT   = -g -mcpu=8540 -mstrict-align -msoft-float -mabi=no-spe -ansi -fno-builtin -Wall -I$(WIND_HOME)/components/windml-4.2/h -I$(WIND_HOME)/components/dcom-2.3/h -I$(WIND_HOME)/components/opc-3.1/h -I$(WIND_HOME)/components/webcli-4.5/target/h -I$(WIND_HOME)/components/webservices-1.4/h -I$(WIND_HOME)/components/windml-4.2/osconfig/vxworks/src -I$(WIND_HOME)/components/windml-4.2/osconfig/vxworks/h -I. -I$(TGT_DIR)/config/all -I$(TGT_DIR)/h -I$(TGT_DIR)/h/wrn/coreip -I$(TGT_DIR)/src/config -I$(TGT_DIR)/config/comps/src -I$(TGT_DIR)/config/comps/src/dosfs2 -I$(TGT_DIR)/src/drv -DCPU=PPC85XX -DTOOL_FAMILY=gnu -DTOOL=gnu -D_WRS_KERNEL
CPP              = ccppc -E -P
EXTRA_MODULES    = $(SUB_TARGETS) ../libtffs.a ../zlib_drv_vx63.o
HEX_FLAGS        = 
LD               = ldppc
LDFLAGS          = -X -N
LD_LINK_PATH     = -L$(TGT_DIR)/lib/ppc/PPC32/sfcommon_ppc85XX_e500v2 -L$(TGT_DIR)/lib/ppc/PPC32/sfgnu -L$(TGT_DIR)/lib/ppc/PPC32/sfcommon -L$(WS_ROOT_DIR)/obj/vxworks-6.3/krnl/lib/ppc/PPC32/gnu -L$(WS_ROOT_DIR)/obj/vxworks-6.3/krnl/lib/ppc/PPC32/common
LD_PARTIAL       = ccppc -r -nostdlib -Wl,-X
LD_PARTIAL_FLAGS = -X -r
LIBS             = $(VX_OS_LIBS)
NM               = nmppc
OPTION_DEFINE_MACRO = -D
OPTION_DEPEND    = -M -w
OPTION_GENERATE_DEPENDENCY_FILE = -MD
OPTION_INCLUDE_DIR = -I
OPTION_LANG_C    = -xc
OPTION_UNDEFINE_MACRO = -U
POST_HEX_BUILD_RULE = 
ROM_LINK_ADRS    = fff40000
ROM_SIZE         = 000c0000 # number of bytes of ROM space
ROM_TEXT_ADRS    = fff40100 # ROM entry address
ROM_WARM_ADRS    = fff40108 # ROM warm entry address
SIZE             = sizeppc
TOOL_FAMILY      = gnu
USR_ENTRY        = usrInit
VMA_START        = 0x0
POST_BUILD_RULE  = 
endif

ifeq ($(BUILD_SPEC),default_romResident)
AR               = arppc
AS               = ccppc
BOOT_EXTRA       = 
CC               = ccppc
CC_ARCH_SPEC     = -mcpu=8540 -mstrict-align -msoft-float -mabi=no-spe
CFLAGS           = -g -mcpu=8540 -mstrict-align -msoft-float -mabi=no-spe -ansi -fno-builtin -Wall -I$(PRJ_DIR) -I$(PRJ_DIR)/../cds8548 -I$(TGT_DIR)/h -I$(TGT_DIR)/config/comps/src -I$(TGT_DIR)/h/wrn/coreip -I$(TGT_DIR)/src/drv -DCPU=PPC85XX -DTOOL_FAMILY=gnu -DTOOL=gnu -DPRJ_BUILD -D_WRS_KERNEL -I$(WIND_HOME)/components/windml-4.2/h -I$(WIND_HOME)/components/dcom-2.3/h -I$(WIND_HOME)/components/opc-3.1/h -I$(WIND_HOME)/components/webcli-4.5/target/h -I$(WIND_HOME)/components/webservices-1.4/h -I$(WIND_HOME)/components/windml-4.2/osconfig/vxworks/src -I$(WIND_HOME)/components/windml-4.2/osconfig/vxworks/h
CFLAGS_AS        = -g -mcpu=8540 -mstrict-align -msoft-float -mabi=no-spe -ansi -fno-builtin -xassembler-with-cpp -I$(PRJ_DIR) -I$(PRJ_DIR)/../cds8548 -I$(TGT_DIR)/h -I$(TGT_DIR)/config/comps/src -I$(TGT_DIR)/h/wrn/coreip -I$(TGT_DIR)/src/drv -DCPU=PPC85XX -DTOOL_FAMILY=gnu -DTOOL=gnu -DPRJ_BUILD -D_WRS_KERNEL -I$(WIND_HOME)/components/windml-4.2/h -I$(WIND_HOME)/components/dcom-2.3/h -I$(WIND_HOME)/components/opc-3.1/h -I$(WIND_HOME)/components/webcli-4.5/target/h -I$(WIND_HOME)/components/webservices-1.4/h -I$(WIND_HOME)/components/windml-4.2/osconfig/vxworks/src -I$(WIND_HOME)/components/windml-4.2/osconfig/vxworks/h
CFLAGS_AS_PROJECT = -g -mcpu=8540 -mstrict-align -msoft-float -mabi=no-spe -ansi -fno-builtin -I$(WIND_HOME)/components/windml-4.2/h -I$(WIND_HOME)/components/dcom-2.3/h -I$(WIND_HOME)/components/opc-3.1/h -I$(WIND_HOME)/components/webcli-4.5/target/h -I$(WIND_HOME)/components/webservices-1.4/h -I$(WIND_HOME)/components/windml-4.2/osconfig/vxworks/src -I$(WIND_HOME)/components/windml-4.2/osconfig/vxworks/h -I. -I$(TGT_DIR)/config/all -I$(TGT_DIR)/h -I$(TGT_DIR)/h/wrn/coreip -I$(TGT_DIR)/src/config -I$(TGT_DIR)/config/comps/src -I$(TGT_DIR)/config/comps/src/dosfs2 -I$(TGT_DIR)/src/drv -DCPU=PPC85XX -DTOOL_FAMILY=gnu -DTOOL=gnu -D_WRS_KERNEL -xassembler-with-cpp
CFLAGS_PROJECT   = -g -mcpu=8540 -mstrict-align -msoft-float -mabi=no-spe -ansi -fno-builtin -Wall -I$(WIND_HOME)/components/windml-4.2/h -I$(WIND_HOME)/components/dcom-2.3/h -I$(WIND_HOME)/components/opc-3.1/h -I$(WIND_HOME)/components/webcli-4.5/target/h -I$(WIND_HOME)/components/webservices-1.4/h -I$(WIND_HOME)/components/windml-4.2/osconfig/vxworks/src -I$(WIND_HOME)/components/windml-4.2/osconfig/vxworks/h -I. -I$(TGT_DIR)/config/all -I$(TGT_DIR)/h -I$(TGT_DIR)/h/wrn/coreip -I$(TGT_DIR)/src/config -I$(TGT_DIR)/config/comps/src -I$(TGT_DIR)/config/comps/src/dosfs2 -I$(TGT_DIR)/src/drv -DCPU=PPC85XX -DTOOL_FAMILY=gnu -DTOOL=gnu -D_WRS_KERNEL
CPP              = ccppc -E -P
EXTRA_MODULES    = $(SUB_TARGETS)
HEX_FLAGS        = 
LD               = ldppc
LDFLAGS          = -X -N
LD_LINK_PATH     = -L$(TGT_DIR)/lib/ppc/PPC85XX/gnu -L$(TGT_DIR)/lib/ppc/PPC85XX/common -L$(TGT_DIR)/lib/ppc/PPC32/sfgnu_ppc85XX -L$(TGT_DIR)/lib/ppc/PPC32/sfcommon_ppc85XX -L$(TGT_DIR)/lib/ppc/PPC32/sfgnu -L$(TGT_DIR)/lib/ppc/PPC32/sfcommon -L$(WS_ROOT_DIR)/obj/vxworks-6.3/krnl/lib/ppc/PPC32/gnu -L$(WS_ROOT_DIR)/obj/vxworks-6.3/krnl/lib/ppc/PPC32/common -L$(WIND_HOME)/components/obj/vxworks-6.3/krnl/lib/ppc/PPC32/gnu -L$(WIND_HOME)/components/obj/vxworks-6.3/krnl/lib/ppc/PPC32/common
LD_PARTIAL       = ccppc -r -nostdlib -Wl,-X
LD_PARTIAL_FLAGS = -X -r
LIBS             = $(VX_OS_LIBS)
NM               = nmppc
OPTION_DEFINE_MACRO = -D
OPTION_DEPEND    = -M -w
OPTION_GENERATE_DEPENDENCY_FILE = -MD
OPTION_INCLUDE_DIR = -I
OPTION_LANG_C    = -xc
OPTION_UNDEFINE_MACRO = -U
ROM_LINK_ADRS    = fff00000
ROM_SIZE         = 00100000 # number of bytes of ROM space
ROM_TEXT_ADRS    = fff00100 # ROM entry address
ROM_WARM_ADRS    = fff00108 # ROM warm entry address
SIZE             = sizeppc
TOOL_FAMILY      = gnu
USR_ENTRY        = usrInit
VMA_START        = 0x0
POST_BUILD_RULE  = 
POST_HEX_BUILD_RULE = 
endif

# override make definitions only below this line


# override make definitions only above this line

include $(TGT_DIR)/h/make/rules.project


## build-configuration info

sysALib.o: $(PRJ_DIR)/prjParams.h

ifeq ($(BUILD_SPEC),default)

usrAppInit.o:
	$(CC) $(CFLAGS) -c $(PRJ_DIR)/usrAppInit.c

usrRtpAppInit.o:
	$(CC) $(CFLAGS) -c $(PRJ_DIR)/usrRtpAppInit.c

sysMotTsecEnd.o:
	$(CC) $(CFLAGS) -c $(PRJ_DIR)/../../bsp_files/PPC8548/sysMotTsecEnd.c

motTsecEnd.o:
	$(CC) $(CFLAGS) -c $(PRJ_DIR)/../../bsp_files/PPC8548/motTsecEnd.c

bspDriver.o:
	$(CC) $(CFLAGS) -c $(PRJ_DIR)/../../bsp_files/bspDriver.c

bspChassis.o:
	$(CC) $(CFLAGS) -c $(PRJ_DIR)/../../bsp_files/bspChassis.c

BspSpi.o:
	$(CC) $(CFLAGS) -c $(PRJ_DIR)/../../bsp_files/PPC8548/BspSpi.c

sysTffs.o:
	$(CC) $(CFLAGS) -c $(PRJ_DIR)/../../bsp_files/sysTffs.c

usrTffs.o:
	$(CC) $(CFLAGS) -c $(PRJ_DIR)/../../bsp_files/PPC8548/usrTffs.c

ftpd6Lib.o:
	$(CC) $(CFLAGS) -c $(PRJ_DIR)/../../bsp_files/ftpd6Lib.c

biosmain.o:
	$(CC) $(CFLAGS) -c $(PRJ_DIR)/../../bsp_files/biosmain.c

hardware.o:
	$(CC) $(CFLAGS) -c $(PRJ_DIR)/../../bsp_files/hardware.c

ivm_core.o:
	$(CC) $(CFLAGS) -c $(PRJ_DIR)/../../bsp_files/ivm_core.c

ispvm_ui.o:
	$(CC) $(CFLAGS) -c $(PRJ_DIR)/../../bsp_files/ispvm_ui.c

biosmain.o:
	$(CC) $(CFLAGS) -c $(PRJ_DIR)/biosmain.c

excArchLib.o:
	$(CC) $(CFLAGS) -c $(PRJ_DIR)/../../bsp_files/PPC8548/excArchLib.c
endif

ifeq ($(BUILD_SPEC),default_rom)

usrAppInit.o:
	$(CC) $(CFLAGS) -c $(PRJ_DIR)/usrAppInit.c

usrRtpAppInit.o:
	$(CC) $(CFLAGS) -c $(PRJ_DIR)/usrRtpAppInit.c

sysMotTsecEnd.o:
	$(CC) $(CFLAGS) -c $(PRJ_DIR)/../../bsp_files/PPC8548/sysMotTsecEnd.c

motTsecEnd.o:
	$(CC) $(CFLAGS) -c $(PRJ_DIR)/../../bsp_files/PPC8548/motTsecEnd.c

bspDriver.o:
	$(CC) $(CFLAGS) -c $(PRJ_DIR)/../../bsp_files/bspDriver.c

bspChassis.o:
	$(CC) $(CFLAGS) -c $(PRJ_DIR)/../../bsp_files/bspChassis.c

BspSpi.o:
	$(CC) $(CFLAGS) -c $(PRJ_DIR)/../../bsp_files/PPC8548/BspSpi.c

sysTffs.o:
	$(CC) $(CFLAGS) -c $(PRJ_DIR)/../../bsp_files/sysTffs.c

usrTffs.o:
	$(CC) $(CFLAGS) -c $(PRJ_DIR)/../../bsp_files/PPC8548/usrTffs.c

ftpd6Lib.o:
	$(CC) $(CFLAGS) -c $(PRJ_DIR)/../../bsp_files/ftpd6Lib.c

biosmain.o:
	$(CC) $(CFLAGS) -c $(PRJ_DIR)/../../bsp_files/biosmain.c

hardware.o:
	$(CC) $(CFLAGS) -c $(PRJ_DIR)/../../bsp_files/hardware.c

ivm_core.o:
	$(CC) $(CFLAGS) -c $(PRJ_DIR)/../../bsp_files/ivm_core.c

ispvm_ui.o:
	$(CC) $(CFLAGS) -c $(PRJ_DIR)/../../bsp_files/ispvm_ui.c

biosmain.o:
	$(CC) $(CFLAGS) -c $(PRJ_DIR)/biosmain.c

excArchLib.o:
	$(CC) $(CFLAGS) -c $(PRJ_DIR)/../../bsp_files/PPC8548/excArchLib.c
endif

ifeq ($(BUILD_SPEC),default_romCompress)

usrAppInit.o:
	$(CC) $(CFLAGS) -c $(PRJ_DIR)/usrAppInit.c

usrRtpAppInit.o:
	$(CC) $(CFLAGS) -c $(PRJ_DIR)/usrRtpAppInit.c

sysMotTsecEnd.o:
	$(CC) $(CFLAGS) -c $(PRJ_DIR)/../../bsp_files/PPC8548/sysMotTsecEnd.c

motTsecEnd.o:
	$(CC) $(CFLAGS) -c $(PRJ_DIR)/../../bsp_files/PPC8548/motTsecEnd.c

bspDriver.o:
	$(CC) $(CFLAGS) -c $(PRJ_DIR)/../../bsp_files/bspDriver.c

bspChassis.o:
	$(CC) $(CFLAGS) -c $(PRJ_DIR)/../../bsp_files/bspChassis.c

BspSpi.o:
	$(CC) $(CFLAGS) -c $(PRJ_DIR)/../../bsp_files/PPC8548/BspSpi.c

sysTffs.o:
	$(CC) $(CFLAGS) -c $(PRJ_DIR)/../../bsp_files/sysTffs.c

usrTffs.o:
	$(CC) $(CFLAGS) -c $(PRJ_DIR)/../../bsp_files/PPC8548/usrTffs.c

ftpd6Lib.o:
	$(CC) $(CFLAGS) -c $(PRJ_DIR)/../../bsp_files/ftpd6Lib.c

biosmain.o:
	$(CC) $(CFLAGS) -c $(PRJ_DIR)/../../bsp_files/biosmain.c

hardware.o:
	$(CC) $(CFLAGS) -c $(PRJ_DIR)/../../bsp_files/hardware.c

ivm_core.o:
	$(CC) $(CFLAGS) -c $(PRJ_DIR)/../../bsp_files/ivm_core.c

ispvm_ui.o:
	$(CC) $(CFLAGS) -c $(PRJ_DIR)/../../bsp_files/ispvm_ui.c

biosmain.o:
	$(CC) $(CFLAGS) -c $(PRJ_DIR)/biosmain.c

excArchLib.o:
	$(CC) $(CFLAGS) -c $(PRJ_DIR)/../../bsp_files/PPC8548/excArchLib.c
endif

ifeq ($(BUILD_SPEC),default_romResident)

usrAppInit.o:
	$(CC) $(CFLAGS) -c $(PRJ_DIR)/usrAppInit.c

usrRtpAppInit.o:
	$(CC) $(CFLAGS) -c $(PRJ_DIR)/usrRtpAppInit.c

sysMotTsecEnd.o:
	$(CC) $(CFLAGS) -c $(PRJ_DIR)/../../bsp_files/PPC8548/sysMotTsecEnd.c

motTsecEnd.o:
	$(CC) $(CFLAGS) -c $(PRJ_DIR)/../../bsp_files/PPC8548/motTsecEnd.c

bspDriver.o:
	$(CC) $(CFLAGS) -c $(PRJ_DIR)/../../bsp_files/bspDriver.c

bspChassis.o:
	$(CC) $(CFLAGS) -c $(PRJ_DIR)/../../bsp_files/bspChassis.c

BspSpi.o:
	$(CC) $(CFLAGS) -c $(PRJ_DIR)/../../bsp_files/PPC8548/BspSpi.c

sysTffs.o:
	$(CC) $(CFLAGS) -c $(PRJ_DIR)/../../bsp_files/sysTffs.c

usrTffs.o:
	$(CC) $(CFLAGS) -c $(PRJ_DIR)/../../bsp_files/PPC8548/usrTffs.c

ftpd6Lib.o:
	$(CC) $(CFLAGS) -c $(PRJ_DIR)/../../bsp_files/ftpd6Lib.c

biosmain.o:
	$(CC) $(CFLAGS) -c $(PRJ_DIR)/../../bsp_files/biosmain.c

hardware.o:
	$(CC) $(CFLAGS) -c $(PRJ_DIR)/../../bsp_files/hardware.c

ivm_core.o:
	$(CC) $(CFLAGS) -c $(PRJ_DIR)/../../bsp_files/ivm_core.c

ispvm_ui.o:
	$(CC) $(CFLAGS) -c $(PRJ_DIR)/../../bsp_files/ispvm_ui.c

biosmain.o:
	$(CC) $(CFLAGS) -c $(PRJ_DIR)/biosmain.c

excArchLib.o:
	$(CC) $(CFLAGS) -c $(PRJ_DIR)/../../bsp_files/PPC8548/excArchLib.c
endif


## user defined rules

romStart.o : $(PRJ_DIR)/../../bsp_files/PPC8548/romStart.c
	$(CC) $(OPTION_OBJECT_ONLY) $(CFLAGS) $(PROJECT_BSP_FLAGS_EXTRA) $(ROM_FLAGS_EXTRA) $< -o $@

romInit.o : $(PRJ_DIR)/../../bsp_files/PPC8548/romInit.s
	$(CC) $(OPTION_OBJECT_ONLY) $(CFLAGS_AS) $(PROJECT_BSP_FLAGS_EXTRA) $(ROM_FLAGS_EXTRA) $< -o $@

linkSyms.o : $(PRJ_DIR)/linkSyms.c
	$(CC) $(OPTION_OBJECT_ONLY) $(CFLAGS) $(PROJECT_BSP_FLAGS_EXTRA) $(PRJ_DIR)/linkSyms.c -o $@

sysLib.o : $(PRJ_DIR)/../../bsp_files/PPC8548/sysLib.c
	$(CC) $(OPTION_OBJECT_ONLY) $(CFLAGS) $(PROJECT_BSP_FLAGS_EXTRA) $(PRJ_DIR)/../../bsp_files/PPC8548/sysLib.c -o $@

sysALib.o : $(PRJ_DIR)/../../bsp_files/PPC8548/sysALib.s
	$(AS) $(OPTION_OBJECT_ONLY) $(CFLAGS_AS) $(PROJECT_BSP_FLAGS_EXTRA) $(PRJ_DIR)/../../bsp_files/PPC8548/sysALib.s -o $@

prjConfig.o : $(PRJ_DIR)/prjConfig.c
	$(CC) $(OPTION_OBJECT_ONLY) $(CFLAGS) $(PROJECT_BSP_FLAGS_EXTRA) $(PRJ_DIR)/prjConfig.c -o $@

